#!/bin/bash

CWD="$PWD"
read -p "update?" yn
if $yn in [Yy]* ) sudo apt update;
read -p "upgrade?" yn
if $yn in [Yy]* ) sudo apt full-upgrade -y;
sudo apt -y install php-fpm php-mysql php php-curl php-gd php-intl php-mbstring php-soap php-xml php-xmlrpc php-zip
# Download and install wp-cli
wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
sudo chmod +x wp-cli.phar
sudo mv wp-cli.phar /usr/local/bin/wp
# Download and install robo
# In case you want to use it: https://robo.li
wget http://robo.li/robo.phar
sudo mv robo.phar /usr/bin/robo && sudo chmod +x /usr/bin/robo
read -p "is mysql already installed? [y/n]" yn
case $yn in
  [Yy]* ) read -p "does mysql already have a user with a password? [y/n]" yn
  case $yn in
    [Yy]* )
    read -p "what would you like to call your database? " DB
    echo "please enter the username and password: "
    read -p "Username: " USER
    read -sp "Password: " PW
    sudo mysql -e "CREATE DATABASE $DB DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci; GRANT ALL ON $DB.* TO '$USER'@'localhost' IDENTIFIED BY '$PW'; FLUSH PRIVILEGES;"
    ;;
    [Nn]* )
    read -p "what would you like to call your database? " DB
    echo "please enter the username and password you would like to use: ";
    read -p "Username: " USER
    read -sp "Password: " PW
    sudo mysql -e "CREATE DATABASE $DB DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci; GRANT ALL ON $DB.* TO '$USER'@'localhost' IDENTIFIED BY '$PW'; FLUSH PRIVILEGES;"
    ;;
  esac;
  ;;
  [Nn]* )
  echo installing mysql...
  sudo apt-get -y install mysql-server mysql-client
  read -p "what would you like to call your database? " DB
  echo "please enter the username and password you would like to use: ";
  read -p "Username: " USER
  read -sp "Password: " PW
  sudo mysql -e "CREATE DATABASE $DB DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci; GRANT ALL ON $DB.* TO '$USER'@'localhost' IDENTIFIED BY '$PW'; FLUSH PRIVILEGES;"
  ;;
esac;
./lsp-wp-install $DB $USER $PW LSP_WP
cd LSP_UI
yarn;
