#!/bin/bash

# this file has been moved to /usr/local/bin/lsp-start.
# You may run lsp-start from any working directory and it will
# run the command below. The command below is run automatically
# as a node child_process when running the start script in
# LSP_UI (after changing dir to this root).
# It is included here for completeness.

sudo wp server --host=localhost --port=80 --docroot=./ --allow-root
