<?php

function lsp_slider_meta_box_config() {
  return new LSP_MB([
    'id' => 'lsp_slider_settings',
    'title' => esc_html__('Slider Settings', 'lsp'),
    'post_types' => ['lsp_slider'],
    'context' => 'advanced',
    'priority' => 'high',
    'autosave' => true,
    'assets_url' => 'assets',
    'rest_base' => 'sliders',
    'fields' => [
      [
        'id' => 'slider_gallery',
        'type' => 'media',
        'name' => esc_html__('slider Gallery', 'lsp'),
        'description' => esc_html__('upload images to this slider', 'lsp'),
        'attributes' => [
          'caption' => 'image caption',
          'link' => 'link',
          'target' => false,
        ],
        'value' => '',
      ],
      [
        'id' => 'speed',
        'type' => 'number',
        'name' => esc_html__('speed', 'lsp'),
        'description' => esc_html__('how fast images change', 'lsp'),
        'std' => '4500',
        'placeholder' => esc_html__('4500', 'lsp'),
        'min' => '100',
        'max' => '999999999',
        'step' => '100',
        'value' => '',
      ],
      [
        'id' => 'transitionspeed',
        'type' => 'number',
        'name' => esc_html__('Transition Speed', 'lsp'),
        'description' => esc_html__('The speed at which the slider changes from one image to the next', 'lsp'),
        'std' => '1',
        'placeholder' => esc_html__('1', 'lsp'),
        'min' => '0.01',
        'max' => '3600',
        'step' => 'any',
        'value' => '',
      ],
      [
        'id' => 'animation',
        'name' => esc_html__('Animation', 'lsp'),
        'type' => 'select',
        'description' => esc_html__('the kind of animation to use for the transition', 'lsp'),
        'placeholder' => esc_html__('Select an Item', 'lsp'),
        'options' => [
          'fade',
          'slide',
        ],
        'value' => '',
      ],
      [
        'id' => 'direction',
        'name' => esc_html__('Direction', 'lsp'),
        'type' => 'select',
        'description' => esc_html__('direction for slides to move (if slide animation selected)', 'lsp'),
        'placeholder' => esc_html__('Select an Item', 'lsp'),
        'options' => [
          'left',
          'right',
        ],
        'value' => '',
      ],
      [
        'id' => 'inview',
        'type' => 'number',
        'name' => esc_html__('inview', 'lsp'),
        'description' => esc_html__('how many images in view', 'lsp'),
        'std' => '1',
        'placeholder' => esc_html__('1', 'lsp'),
        'min' => '1',
        'max' => '999999999',
        'step' => '1',
        'value' => '',
      ],
      [
        'id' => 'advance',
        'type' => 'number',
        'name' => esc_html__('advance', 'lsp'),
        'description' => esc_html__('how many images to advance per animation', 'lsp'),
        'std' => '1',
        'placeholder' => esc_html__('1', 'lsp'),
        'min' => '1',
        'max' => '999999999',
        'step' => '1',
        'value' => '',
      ],
      [
        'id' => 'auto',
        'name' => esc_html__('Auto Play', 'lsp'),
        'type' => 'checkbox',
        'description' => esc_html__('automatically start slider?', 'lsp'),
        'checked' => false,
        'value' => 'auto',
      ],
      [
        'id' => 'arrows',
        'name' => esc_html__('Arrows', 'lsp'),
        'type' => 'checkbox',
        'description' => esc_html__('should the slider have next and previous arrow controls?', 'lsp'),
        'checked' => false,
        'value' => 'arrows',
      ],
      [
        'id' => 'playpause',
        'name' => esc_html__('Play and Pause Toggle', 'lsp'),
        'type' => 'checkbox',
        'description' => esc_html__('should there be a button to start and stop the slider?', 'lsp'),
        'checked' => false,
        'value' => 'playpause',
      ],
      [
        'id' => 'pauseonhover',
        'name' => esc_html__('Pause On Hover', 'lsp'),
        'type' => 'checkbox',
        'description' => esc_html__('should the slider pause with the mouse hovers over?', 'lsp'),
        'checked' => false,
        'value' => 'pauseonhover',
      ],
    ],
  ]);
}

add_action('save_post', [lsp_slider_meta_box_config(), 'lsp_save_meta_box'], 1, 2);
add_action('add_meta_boxes', [lsp_slider_meta_box_config(), 'lsp_add_meta_box']);
